name: plannex
description: "Plannex"
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  flutter_localizations:
      sdk: flutter
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.9
  table_calendar: ^3.1.2
  day_night_time_picker: ^1.3.1
  intl: ^0.19.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  logger: ^2.6.2
  record: ^6.2.0
  path_provider: ^2.1.2
  firebase_messaging: ^15.2.10
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  flutter_slidable: ^3.1.1
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  package_info_plus: ^8.0.0
  vibration: ^3.1.5
  flutter_ringtone_player: ^4.0.0+4
dev_dependencies:
  build_runner: ^2.4.6
  flutter_native_splash: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  commitlint_cli: ^0.8.1
  husky: ^0.1.7
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
